clean:
	rm abstract.aux
	rm acronimos.aux
	rm agradecimentos.aux
	rm sumario.aux
	rm introduction.aux
	rm thesis_text.aux
	rm thesis_text.lof
	rm thesis_text.log
	rm thesis_text.lot
	rm thesis_text.pdf
	rm thesis_text.toc
	rm thesis_text.synctex.gz
	rm thesis_text.idx
