clean:
	rm abstract.aux
	rm acronimos.aux
	rm agradecimentos.aux
	rm sumario.aux
	rm introduction.aux
	rm background.aux
	rm identityHealthcare.aux
	rm useCases.aux
	rm thesis_text.aux
	rm thesis_text.log
	rm thesis_text.pdf
	rm thesis_text.synctex.gz
	rm thesis_text.idx
	rm thesis_text.bbl 
	rm thesis_text.blg 
	rm thesis_text.out
